### ISSUE TITLE
doc the differences between other similar open source projects

### ISSUE THREAD

**Issue by panpan0000** [miragedebug/miragedebug#1]
example : https://github.com/nocalhost/nocalhost

**Comment by kebe7jun** [comment]
Nocalhost is a good plugin that indeed has similar capabilities. In my view, Nocalhost is more focused on development. It injects new containers into Pods, processes local code to run in the Pod, and utilizes the compilation capabilities provided by the cloud Pod for code compilation and debugging. However, sometimes we can't perform compilation well inside the Pod (for example, due to network issues or dependencies, local might be more reliable).

In the design scenario of MirageDebug, the main objective is to facilitate more convenient debugging of Pods. It uses locally compiled binary files (compiled at debug time), and via the port mapping of the Pod, it runs the local code directly inside the Pod. In this way, the local IDE can be used directly for debugging. At the same time, it will not modify the image of the Pod, which ensures that it can also run normally under some special circumstances (for example, with pre-installed software) and ensures the consistency between the application being debugged and the live application.
